name: smartdex
description: Smartdex is Real Life Pokedex from Pokemon Universe.

version: 1.1.0+7

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  cached_network_image: ^2.2.0+1
  #admob_flutter: ^0.3.4
  http: ^0.12.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/Pokedex.json
